In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
data = pd.read_csv("Customer.csv")

In [30]:
data.head()

   gender  age  salary  purchased
0    Male   19   19000          0
1    Male   35   20000          0
2  Female   26   43000          0
3  Female   27   57000          0
4    Male   19   76000          0

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   gender     400 non-null    object
 1   age        400 non-null    int64
 2   salary     400 non-null    int64
 3   purchased  400 non-null    int64
dtypes: int64(3), object(1)
memory usage: 12.6+ KB

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [37]:
# first step
att = data[["age", "salary"]]
allclass = data["purchased"]

att_train, att_test, class_train, class_test = train_test_split(att, allclass, random_state = 0, train_size = .7)


#secound step
scaler = StandardScaler()
scaler.fit(att_train)
att_train[[ "age", "salary"]] = scaler.transform(att_train)

model = KNeighborsClassifier(n_neighbors = 3)
model.fit(att_train, class_train)

# third step
model.score(scaler.transform(att_test), class_test)

C:\Users\dekdo\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

0.9083333333333333

In [45]:
scaler.inverse_transform(att_train)
# att_train[[ "age", "salary"]]

array([[2.60e+01, 1.50e+04],
       [6.00e+01, 1.02e+05],
       [3.80e+01, 1.12e+05],
       [4.00e+01, 1.07e+05],
       [4.20e+01, 5.30e+04],
       [3.50e+01, 5.90e+04],
       [4.80e+01, 4.10e+04],
       [4.80e+01, 1.34e+05],
       [3.80e+01, 1.13e+05],
       [2.90e+01, 1.48e+05],
       [2.60e+01, 1.50e+04],
       [6.00e+01, 4.20e+04],
       [2.40e+01, 1.90e+04],
       [4.20e+01, 1.49e+05],
       [4.60e+01, 9.60e+04],
       [2.80e+01, 5.90e+04],
       [3.90e+01, 9.60e+04],
       [2.80e+01, 8.90e+04],
       [4.10e+01, 7.20e+04],
       [4.50e+01, 2.60e+04],
       [3.30e+01, 6.90e+04],
       [2.00e+01, 8.20e+04],
       [3.10e+01, 7.40e+04],
       [4.20e+01, 8.00e+04],
       [3.50e+01, 7.20e+04],
       [3.30e+01, 1.49e+05],
       [4.00e+01, 7.10e+04],
       [5.10e+01, 1.46e+05],
       [4.60e+01, 7.90e+04],
       [3.50e+01, 7.50e+04],
       [3.80e+01, 5.10e+04],
       [3.60e+01, 7.50e+04],
       [3.70e+01, 7.80e+04],
       [3.80e+01, 6.10e+04],
       [6.00e+01, 1.08e+05],
       [2.00e+01, 8.20e+04],
       [5.70e+01, 7.40e+04],
       [4.20e+01, 6.50e+04],
       [2.60e+01, 8.00e+04],
       [4.60e+01, 1.17e+05],
       [3.50e+01, 6.10e+04],
       [2.10e+01, 6.80e+04],
       [2.80e+01, 4.40e+04],
       [4.10e+01, 8.70e+04],
       [3.70e+01, 3.30e+04],
       [2.70e+01, 9.00e+04],
       [3.90e+01, 4.20e+04],
       [2.80e+01, 1.23e+05],
       [3.10e+01, 1.18e+05],
       [2.50e+01, 8.70e+04],
       [3.50e+01, 7.10e+04],
       [3.70e+01, 7.00e+04],
       [3.50e+01, 3.90e+04],
       [4.70e+01, 2.30e+04],
       [3.50e+01, 1.47e+05],
       [4.80e+01, 1.38e+05],
       [2.60e+01, 8.60e+04],
       [2.50e+01, 7.90e+04],
       [5.20e+01, 1.38e+05],
       [5.10e+01, 2.30e+04],
       [3.50e+01, 6.00e+04],
       [3.30e+01, 1.13e+05],
       [3.00e+01, 1.07e+05],
       [4.80e+01, 3.30e+04],
       [4.10e+01, 8.00e+04],
       [4.80e+01, 9.60e+04],
       [3.10e+01, 1.80e+04],
       [3.10e+01, 7.10e+04],
       [4.30e+01, 1.29e+05],
       [5.90e+01, 7.60e+04],
       [1.80e+01, 4.40e+04],
       [3.60e+01, 1.18e+05],
       [4.20e+01, 9.00e+04],
       [4.70e+01, 3.00e+04],
       [2.60e+01, 4.30e+04],
       [4.00e+01, 7.80e+04],
       [4.60e+01, 5.90e+04],
       [5.90e+01, 4.20e+04],
       [4.60e+01, 7.40e+04],
       [3.50e+01, 9.10e+04],
       [2.80e+01, 5.90e+04],
       [4.00e+01, 5.70e+04],
       [5.90e+01, 1.43e+05],
       [5.70e+01, 2.60e+04],
       [5.20e+01, 3.80e+04],
       [4.70e+01, 1.13e+05],
       [5.30e+01, 1.43e+05],
       [3.50e+01, 2.70e+04],
       [5.80e+01, 1.01e+05],
       [4.50e+01, 4.50e+04],
       [2.30e+01, 8.20e+04],
       [4.60e+01, 2.30e+04],
       [4.20e+01, 6.50e+04],
       [2.80e+01, 8.40e+04],
       [3.80e+01, 5.90e+04],
       [2.60e+01, 8.40e+04],
       [2.90e+01, 2.80e+04],
       [3.70e+01, 7.10e+04],
       [2.20e+01, 5.50e+04],
       [4.80e+01, 3.50e+04],
       [4.90e+01, 2.80e+04],
       [3.80e+01, 6.50e+04],
       [2.70e+01, 1.70e+04],
       [4.60e+01, 2.80e+04],
       [4.80e+01, 1.41e+05],
       [2.60e+01, 1.70e+04],
       [3.50e+01, 9.70e+04],
       [3.90e+01, 5.90e+04],
       [2.40e+01, 2.70e+04],
       [3.20e+01, 1.80e+04],
       [4.60e+01, 8.80e+04],
       [3.50e+01, 5.80e+04],
       [5.60e+01, 6.00e+04],
       [4.70e+01, 3.40e+04],
       [4.00e+01, 7.20e+04],
       [3.20e+01, 1.00e+05],
       [1.90e+01, 2.10e+04],
       [2.50e+01, 9.00e+04],
       [3.50e+01, 8.80e+04],
       [2.80e+01, 3.20e+04],
       [5.00e+01, 2.00e+04],
       [4.00e+01, 5.90e+04],
       [5.00e+01, 4.40e+04],
       [3.50e+01, 7.20e+04],
       [4.00e+01, 1.42e+05],
       [4.60e+01, 3.20e+04],
       [3.90e+01, 7.10e+04],
       [2.00e+01, 7.40e+04],
       [2.90e+01, 7.50e+04],
       [3.10e+01, 7.60e+04],
       [4.70e+01, 2.50e+04],
       [4.00e+01, 6.10e+04],
       [3.40e+01, 1.12e+05],
       [3.80e+01, 8.00e+04],
       [4.20e+01, 7.50e+04],
       [4.70e+01, 4.70e+04],
       [3.90e+01, 7.50e+04],
       [1.90e+01, 2.50e+04],
       [3.70e+01, 8.00e+04],
       [3.60e+01, 6.00e+04],
       [4.10e+01, 5.20e+04],
       [3.60e+01, 1.25e+05],
       [4.80e+01, 2.90e+04],
       [3.60e+01, 1.26e+05],
       [5.10e+01, 1.34e+05],
       [2.70e+01, 5.70e+04],
       [3.80e+01, 7.10e+04],
       [3.90e+01, 6.10e+04],
       [2.20e+01, 2.70e+04],
       [3.30e+01, 6.00e+04],
       [4.80e+01, 7.40e+04],
       [5.80e+01, 2.30e+04],
       [5.30e+01, 7.20e+04],
       [3.20e+01, 1.17e+05],
       [5.40e+01, 7.00e+04],
       [3.00e+01, 8.00e+04],
       [5.80e+01, 9.50e+04],
       [2.60e+01, 5.20e+04],
       [4.50e+01, 7.90e+04],
       [2.40e+01, 5.50e+04],
       [4.00e+01, 7.50e+04],
       [3.30e+01, 2.80e+04],
       [4.40e+01, 1.39e+05],
       [2.20e+01, 1.80e+04],
       [3.30e+01, 5.10e+04],
       [4.30e+01, 1.33e+05],
       [2.40e+01, 3.20e+04],
       [4.60e+01, 2.20e+04],
       [3.50e+01, 5.50e+04],
       [5.40e+01, 1.04e+05],
       [4.80e+01, 1.19e+05],
       [3.50e+01, 5.30e+04],
       [3.70e+01, 1.44e+05],
       [2.30e+01, 6.60e+04],
       [3.70e+01, 1.37e+05],
       [3.10e+01, 5.80e+04],
       [3.30e+01, 4.10e+04],
       [4.50e+01, 2.20e+04],
       [3.00e+01, 1.50e+04],
       [1.90e+01, 1.90e+04],
       [4.90e+01, 7.40e+04],
       [3.90e+01, 1.22e+05],
       [3.50e+01, 7.30e+04],
       [3.90e+01, 7.10e+04],
       [2.40e+01, 2.30e+04],
       [4.10e+01, 7.20e+04],
       [2.90e+01, 8.30e+04],
       [5.40e+01, 2.60e+04],
       [3.50e+01, 4.40e+04],
       [3.70e+01, 7.50e+04],
       [2.90e+01, 4.70e+04],
       [3.10e+01, 6.80e+04],
       [4.20e+01, 5.40e+04],
       [3.00e+01, 1.35e+05],
       [5.20e+01, 1.14e+05],
       [5.00e+01, 3.60e+04],
       [5.60e+01, 1.33e+05],
       [2.90e+01, 6.10e+04],
       [3.00e+01, 8.90e+04],
       [2.60e+01, 1.60e+04],
       [3.30e+01, 3.10e+04],
       [4.10e+01, 7.20e+04],
       [3.60e+01, 3.30e+04],
       [5.50e+01, 1.25e+05],
       [4.80e+01, 1.31e+05],
       [4.10e+01, 7.10e+04],
       [3.00e+01, 6.20e+04],
       [3.70e+01, 7.20e+04],
       [4.10e+01, 6.30e+04],
       [5.80e+01, 4.70e+04],
       [3.00e+01, 1.16e+05],
       [2.00e+01, 4.90e+04],
       [3.70e+01, 7.40e+04],
       [4.10e+01, 5.90e+04],
       [4.90e+01, 8.90e+04],
       [2.80e+01, 7.90e+04],
       [5.30e+01, 8.20e+04],
       [4.00e+01, 5.70e+04],
       [6.00e+01, 3.40e+04],
       [3.50e+01, 1.08e+05],
       [2.10e+01, 7.20e+04],
       [3.80e+01, 7.10e+04],
       [3.90e+01, 1.06e+05],
       [3.70e+01, 5.70e+04],
       [2.60e+01, 7.20e+04],
       [3.50e+01, 2.30e+04],
       [5.40e+01, 1.08e+05],
       [3.00e+01, 1.70e+04],
       [3.90e+01, 1.34e+05],
       [2.90e+01, 4.30e+04],
       [3.30e+01, 4.30e+04],
       [3.50e+01, 3.80e+04],
       [4.10e+01, 4.50e+04],
       [4.10e+01, 7.20e+04],
       [3.90e+01, 1.34e+05],
       [2.70e+01, 1.37e+05],
       [2.10e+01, 1.60e+04],
       [2.60e+01, 3.20e+04],
       [3.10e+01, 6.60e+04],
       [3.90e+01, 7.30e+04],
       [4.10e+01, 7.90e+04],
       [4.70e+01, 5.00e+04],
       [4.10e+01, 3.00e+04],
       [3.70e+01, 9.30e+04],
       [6.00e+01, 4.60e+04],
       [2.50e+01, 2.20e+04],
       [2.80e+01, 3.70e+04],
       [3.80e+01, 5.50e+04],
       [3.60e+01, 5.40e+04],
       [2.00e+01, 3.60e+04],
       [5.60e+01, 1.04e+05],
       [4.00e+01, 5.70e+04],
       [4.20e+01, 1.08e+05],
       [2.00e+01, 2.30e+04],
       [4.00e+01, 6.50e+04],
       [4.70e+01, 2.00e+04],
       [1.80e+01, 8.60e+04],
       [3.50e+01, 7.90e+04],
       [5.70e+01, 3.30e+04],
       [3.40e+01, 7.20e+04],
       [4.90e+01, 3.90e+04],
       [2.70e+01, 3.10e+04],
       [1.90e+01, 7.00e+04],
       [3.90e+01, 7.90e+04],
       [2.60e+01, 8.10e+04],
       [2.50e+01, 8.00e+04],
       [2.80e+01, 8.50e+04],
       [5.50e+01, 3.90e+04],
       [5.00e+01, 8.80e+04],
       [4.90e+01, 8.80e+04],
       [5.20e+01, 1.50e+05],
       [3.50e+01, 6.50e+04],
       [4.20e+01, 5.40e+04],
       [3.40e+01, 4.30e+04],
       [3.70e+01, 5.20e+04],
       [4.80e+01, 3.00e+04],
       [2.90e+01, 4.30e+04],
       [3.60e+01, 5.20e+04],
       [2.70e+01, 5.40e+04],
       [2.60e+01, 1.18e+05]])

In [46]:
model.predict(att_train)

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [47]:
result = pd.concat([att_train, class_train], axis = 1)
result["predict"] = model.predict(att_train)
result

          age    salary  purchased  predict
92  -1.163172 -1.584970          0        0
223  2.170181  0.930987          1        1
234  0.013305  1.220177          0        1
232  0.209385  1.075582          1        1
377  0.405465 -0.486047          0        0
..        ...       ...        ...      ...
323  0.993704 -1.151185          1        1
192 -0.869053 -0.775237          0        0
117 -0.182774 -0.514966          0        0
47  -1.065133 -0.457127          0        0
172 -1.163172  1.393691          0        0

[280 rows x 4 columns]

In [49]:
model.predict(scaler.transform([[32, 150000]]))

C:\Users\dekdo\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\dekdo\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)